#!/bin/bash
# Build Insaniquarium Deluxe for the Miyoo Mini (armv7 hf, glibc 2.28).
#
# Runs inside the miyoo-builder image. Source and build tree live in the
# miyoo-build volume (Linux side) so the build is fast and survives between
# container runs; /host is the Windows working directory, used only to get the
# source in and the artifacts out.
set -euo pipefail

# Keep the whole log in the volume: the container is disposable and the failure
# is usually well above the end of a long compile line.
mkdir -p /work
exec > >(tee /work/build.log) 2>&1

export PATH=/opt/cmake/bin:$PATH
SYS=/opt/miyoomini-toolchain/arm-linux-gnueabihf/libc

if [ ! -d /work/src/poplib ]; then
  echo "== seeding source into the volume"
  mkdir -p /work
  cp -a /host/insaniquarium-port /work/src
fi

# port/ is cheap to re-copy and is what changes when port.sh is re-run; the
# generated port/winfish tree has to match it. PopLib is re-copied too because
# this port carries a fix in it (openalsoundmanager.cpp); its external/ tree is
# left alone, that is where the expensive clones live.
rm -rf /work/src/port
cp -a /host/insaniquarium-port/port /work/src/port
rm -rf /work/src/poplib/PopLib
cp -a /host/insaniquarium-port/poplib/PopLib /work/src/poplib/PopLib

# libopenmpt's build/ tree is generated by its own autotools build and the
# vendored copy has no build/ at all, but common/version.cpp includes
# ../build/svn_version/svn_version.h. Every macro in it is #ifdef-guarded, so a
# revision of 0 is enough to satisfy the include.
mkdir -p /work/src/poplib/external/libopenmpt/build/svn_version
if [ ! -f /work/src/poplib/external/libopenmpt/build/svn_version/svn_version.h ]; then
  printf '#define OPENMPT_VERSION_SVNVERSION "0"\n' \
    > /work/src/poplib/external/libopenmpt/build/svn_version/svn_version.h
fi

echo "== configure"
# CMAKE_*_FLAGS_INIT from the toolchain file are only read on the first
# configure; afterwards the values live in the cache and the toolchain file is
# not looked at again, so editing it would silently do nothing. Objects stay
# valid, only the cache goes.
rm -f /work/build/CMakeCache.txt
cmake -S /work/src/port -B /work/build -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE=/work/src/port/toolchain-armhf-miyoo.cmake \
  -DWINFISH_SYSROOT="$SYS" \
  -DCMAKE_BUILD_TYPE=Release \
  -DSDLTTF_VENDORED=ON \
  -DPOPLIB_WITH_BASS=OFF \
  -DPOPLIB_SDL_SHARED=ON \
  -DSDL_UNIX_CONSOLE_BUILD=ON \
  -DSDL_TESTS=OFF -DSDL_INSTALL=OFF \
  -DSDL_ALSA=OFF \
  -DALSA_INCLUDE_DIR=/host/alsa-dev/include \
  -DALSA_LIBRARY=/host/alsa-dev/lib/libasound.so

echo "== did OpenAL pick up ALSA? =="
grep -riE "ALSA_LIBRARY" /work/build/CMakeCache.txt || echo "  (not in the cache)"

echo "== build"
cmake --build /work/build --parallel "$(nproc)"

BIN=/work/src/port/bin/Insaniquarium
echo
echo "=== result ==="
file "$BIN"
echo "--- highest glibc version required ---"
arm-linux-gnueabihf-objdump -T "$BIN" | grep -o 'GLIBC_[0-9.]*' | sort -uV | tail -5
echo "--- __libc_csu_init (constructors) ---"
arm-linux-gnueabihf-nm "$BIN" | grep __libc_csu_init || echo "MISSING"
echo "--- libraries needed on the device ---"
arm-linux-gnueabihf-readelf -d "$BIN" | grep NEEDED

mkdir -p /host/out
cp "$BIN" /host/out/Insaniquarium
echo "copied to /host/out/Insaniquarium"
